# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{zomgrss}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Federico Builes"]
  s.date = %q{2010-05-22}
  s.description = %q{Create RSS feeds from Ruby collections.}
  s.email = %q{federico@mheroin.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "examples/active_record_sample.rb",
     "examples/datamapper_sample.rb",
     "lib/zomgrss.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/zomgrss_spec.rb",
     "zomgrss.gemspec"
  ]
  s.homepage = %q{http://github.com/febuiles/zomgrss}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Create RSS feeds from Ruby collections.}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/zomgrss_spec.rb",
     "examples/active_record_sample.rb",
     "examples/datamapper_sample.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<builder>, [">= 0"])
    else
      s.add_dependency(%q<builder>, [">= 0"])
    end
  else
    s.add_dependency(%q<builder>, [">= 0"])
  end
end

